"""Exercise recovery and persisted state through the real executable."""

import json
import os
import struct
import subprocess
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
APP = Path(os.environ.get("CUDA_APP_EXE", ROOT / ".cuda-build/optimized.exe"))
WALLET = ROOT / "btcrecover/test/test-wallets/multibit-wallet.key"
pytestmark = pytest.mark.skipif(
    not APP.exists(),
    reason="Build the isolated optimized executable first",
)


def run_app(directory, tokens, *options):
    """Run an isolated recovery search using only a public test wallet."""
    token_file = directory / "synthetic.txt"
    token_file.write_text(tokens, encoding="utf-8")
    return subprocess.run(
        [
            str(APP),
            "--wallet",
            str(WALLET),
            "--tokenlist",
            str(token_file),
            *options,
        ],
        cwd=directory,
        capture_output=True,
        text=True,
        check=False,
        timeout=60,
    )


def timing_values(output):
    """Extract the exact non-historical counters from program output."""
    lines = [
        line for line in output.splitlines() if line.startswith("TIMINGS ")
    ]
    assert len(lines) == 1
    return json.loads(lines[0][len("TIMINGS ") :])


@pytest.mark.parametrize("synchronous", [False, True])
def test_cli_recovers_public_fixture(tmp_path, synchronous):
    options = ["--batch-size", "3", "--timings"]
    if synchronous:
        options.append("--synchronous")
    result = run_app(
        tmp_path,
        "+wrong1 wrong2 btcr-test-password wrong3\n",
        *options,
    )
    assert result.returncode == 0, result.stderr
    assert (tmp_path / "RECOVERED_PASSWORD.txt").read_bytes().strip() == (
        b"btcr-test-password"
    )
    assert "Not found" not in result.stdout
    assert timing_values(result.stdout)["count"] == 3


@pytest.mark.parametrize("value", ["0", "-1", "1048577", "1x"])
def test_invalid_batch_size_is_rejected(tmp_path, value):
    result = run_app(tmp_path, "+wrong\n", "--batch-size", value)
    assert result.returncode != 0
    assert not (tmp_path / "RECOVERED_PASSWORD.txt").exists()


@pytest.mark.parametrize("value", ["0", "-1", "1x", "100000"])
def test_invalid_producers_is_rejected(tmp_path, value):
    result = run_app(tmp_path, "+wrong\n", "--producers", value)
    assert result.returncode != 0
    assert not (tmp_path / "RECOVERED_PASSWORD.txt").exists()


def test_cli_producers_match_single(tmp_path):
    # Permutation-heavy, no recovery: the count must be identical whether the
    # candidates are generated by one thread or by a parallel producer pool.
    tokens = "+ a1 b1 c1\n+ d2\n+ e2\n+ f2\n"
    single = run_app(tmp_path, tokens, "--producers", "1", "--timings")
    assert single.returncode == 0, single.stderr
    assert "Not found" in single.stdout
    baseline = timing_values(single.stdout)["count"]
    for workers in ["2", "4"]:
        parallel = run_app(tmp_path, tokens, "--producers", workers, "--timings")
        assert parallel.returncode == 0, parallel.stderr
        assert "Not found" in parallel.stdout
        assert timing_values(parallel.stdout)["count"] == baseline


def test_cli_producers_recover_public_fixture(tmp_path):
    result = run_app(
        tmp_path,
        "+wrong1 wrong2 btcr-test-password wrong3\n",
        "--producers",
        "4",
        "--batch-size",
        "3",
        "--timings",
    )
    assert result.returncode == 0, result.stderr
    assert (tmp_path / "RECOVERED_PASSWORD.txt").read_bytes().strip() == (
        b"btcr-test-password"
    )


def test_cli_complete_and_resume_have_exact_counts(tmp_path):
    checkpoint = tmp_path / "synthetic.bin"
    result = run_app(
        tmp_path,
        "+ab cd\n+ef\n",
        "--batch-size",
        "3",
        "--timings",
        "--autosave",
        str(checkpoint),
    )
    assert result.returncode == 0, result.stderr
    assert timing_values(result.stdout)["count"] == 4
    assert "Not found" in result.stdout
    data = checkpoint.read_bytes()
    # Existing layout: two 512-byte paths, three counters, two offsets.
    combo, total, checked = struct.unpack_from("<QQQ", data, 1024)
    assert combo == total == 2
    assert checked == 4
    resumed = subprocess.run(
        [
            str(APP),
            "--restore",
            str(checkpoint),
            "--batch-size",
            "3",
            "--timings",
        ],
        cwd=tmp_path,
        capture_output=True,
        text=True,
        check=False,
        timeout=60,
    )
    assert resumed.returncode == 0, resumed.stderr
    assert timing_values(resumed.stdout)["count"] == 0
    assert "0 passwords" in resumed.stdout


def test_cli_mid_typo_resume_preserves_remaining_count(tmp_path):
    checkpoint = tmp_path / "synthetic.bin"
    options = [
        "--batch-size",
        "3",
        "--typos",
        "1",
        "--typos-repeat",
        "--typos-delete",
        "--timings",
    ]
    result = run_app(
        tmp_path,
        "+ab\n",
        *options,
        "--autosave",
        str(checkpoint),
    )
    assert result.returncode == 0, result.stderr
    assert timing_values(result.stdout)["count"] == 5
    data = bytearray(checkpoint.read_bytes())
    struct.pack_into("<Q", data, 1024, 0)
    struct.pack_into("<Q", data, 1040, 2)
    struct.pack_into("<QQ", data, 1048, 0, 2)
    checkpoint.write_bytes(data)
    result = subprocess.run(
        [str(APP), "--restore", str(checkpoint), *options],
        cwd=tmp_path,
        capture_output=True,
        text=True,
        check=False,
        timeout=60,
    )
    assert result.returncode == 0, result.stderr
    assert timing_values(result.stdout)["count"] == 3
